name: GiveEveryDamnAchievement
main: me.blha303.giveeverydamnachievement.Main
version: 4
commands:
  giveeverydamnachievement:
    description: Give the specified players every damn achievement
    usage: /giveeverydamnachievement <player> [player...]
    aliases: [geda, giveallachievements, giveachievements, giveallach, giveach, allach]
permissions:
  giveeverydamnachievement.use:
    description: Lets the player use the command
    default: op
